"""Initial schema

Revision ID: 65f00fee2244
Revises: 
Create Date: 2026-03-19 12:40:06.526715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65f00fee2244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_window',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campground_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.String(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_window_campground_id'), 'availability_window', ['campground_id'], unique=False)
    op.create_index(op.f('ix_availability_window_id'), 'availability_window', ['id'], unique=False)
    op.create_table('watch_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campground_id', sa.Integer(), nullable=False),
    sa.Column('campground_name', sa.String(), nullable=False),
    sa.Column('date_range_start', sa.String(), nullable=False),
    sa.Column('date_range_end', sa.String(), nullable=False),
    sa.Column('days_of_week', sa.JSON(), nullable=False),
    sa.Column('site_type', sa.String(), nullable=False),
    sa.Column('site_numbers', sa.JSON(), nullable=True),
    sa.Column('amenity_filters', sa.JSON(), nullable=True),
    sa.Column('alert_email', sa.String(), nullable=False),
    sa.Column('pushover_key', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_expanded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watch_templates_id'), 'watch_templates', ['id'], unique=False)
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campground_id', sa.Integer(), nullable=False),
    sa.Column('campground_name', sa.String(), nullable=False),
    sa.Column('checkin_date', sa.String(), nullable=False),
    sa.Column('checkout_date', sa.String(), nullable=False),
    sa.Column('site_type', sa.String(), nullable=False),
    sa.Column('site_numbers', sa.JSON(), nullable=True),
    sa.Column('amenity_filters', sa.JSON(), nullable=True),
    sa.Column('alert_email', sa.String(), nullable=False),
    sa.Column('pushover_key', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('alerted', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_status', sa.String(), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campground_id', 'checkin_date', 'checkout_date', 'site_type', name='unique_watch')
    )
    op.create_index(op.f('ix_watches_campground_id'), 'watches', ['campground_id'], unique=False)
    op.create_index(op.f('ix_watches_id'), 'watches', ['id'], unique=False)
    op.create_table('alert_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_log_id'), 'alert_log', ['id'], unique=False)
    op.create_index(op.f('ix_alert_log_watch_id'), 'alert_log', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_log_watch_id'), table_name='alert_log')
    op.drop_index(op.f('ix_alert_log_id'), table_name='alert_log')
    op.drop_table('alert_log')
    op.drop_index(op.f('ix_watches_id'), table_name='watches')
    op.drop_index(op.f('ix_watches_campground_id'), table_name='watches')
    op.drop_table('watches')
    op.drop_index(op.f('ix_watch_templates_id'), table_name='watch_templates')
    op.drop_table('watch_templates')
    op.drop_index(op.f('ix_availability_window_id'), table_name='availability_window')
    op.drop_index(op.f('ix_availability_window_campground_id'), table_name='availability_window')
    op.drop_table('availability_window')
    # ### end Alembic commands ###
